version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Build started on `date`
      # Build the Docker images
      - echo Building the production Docker image...
      - docker build -t walkerperedo/dkr-multicontainer-app-order ./order
      - docker build -t walkerperedo/dkr-multicontainer-app-recipes ./recipes
      - docker build -t walkerperedo/dkr-multicontainer-app-warehouse ./warehouse
      - docker build -t walkerperedo/dkr-multicontainer-app-nginx ./proxy
      # Log in to the Docker CLI
      - echo "$DOCKER_PW" | docker login -u "walkerperedo" --password-stdin
  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      - docker push walkerperedo/dkr-multicontainer-app-order
      - docker push walkerperedo/dkr-multicontainer-app-recipes
      - docker push walkerperedo/dkr-multicontainer-app-warehouse
      - docker push walkerperedo/dkr-multicontainer-app-nginx
